version: '3.9'

services:
  django:
    container_name: inventory_app
    build: .
    # command: sleep infinity
    # Untuk menjalankan server Django, ganti command di atas menjadi:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - postgres

  postgres:
    container_name: inventory_db
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata